language: python
python:
  - "2.7"

# command to install dependencies
install:
- pip install -r pip_requirements.txt --use-mirrors


# command to run tests
script: source ~/virtualenv/python2.7/bin/activate && python tests.py